version: '3.8'

services:
  signal:
    image: runestone123456789/northy:latest
    container_name: signal
    volumes:
      - .:/app
    command: python /app/cli_signal.py --prod watch
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

#  saxoMarket:
#    image: runestone123456789/northy:latest
#    container_name: saxoMarket
#    volumes:
#      - .:/app
#    command: python /app/cli_saxo.py --prod --profile market watch
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true"

#  saxoLimit:
#    image: runestone123456789/northy:latest
#    container_name: saxoStagingLimit
#    volumes:
#      - .:/app
#    command: python /app/cli_saxo.py --prod --profile limit watch
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true"

  #saxoDev:
  #  image: runestone123456789/northy:latest
  #  container_name: saxoDev
  #  volumes:
  #    - .:/app
  #  command: python /app/cli_saxo.py --prod --profile dev watch
  #  labels:
  #    - "com.centurylinklabs.watchtower.enable=true"

  # Docker Free, doesn't allow 2-way file sync
  # Podman is shit and failed to make it work
  # 
  #noc:
  #  image: runestone123456789/northy:latest
  #  container_name: noc
  #  volumes:
  #    - .:/app
  #    - type: bind
  #      source: /c/Users/User/AppData/Local/Microsoft/Windows/Notifications/wpndatabase.db
  #      target: /host_notifications/wpndatabase.db
  #  command: python /app/cli_noc.py --prod watch
  #  labels:
  #    - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 30 --label-enable
    environment:
      - REPO_USER=${DOCKER_USERNAME}
      - REPO_PASS=${DOCKER_PASSWORD}
