version: '3.8'

services:
  saxo:
    image: runestone123456789/northy:latest
    container_name: saxo
    volumes:
      - .:/app
    command: python /app/cli_saxo.py --prod watch
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  signal:
    image: runestone123456789/northy:latest
    container_name: signal
    volumes:
      - .:/app
    command: python /app/cli_signal.py --prod watch
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  noc:
    image: runestone123456789/northy:latest
    container_name: noc
    volumes:
      - .:/app
      - /c/Users/User/AppData/Local/Microsoft/Windows/Notifications/wpndatabase.db:/host_notifications/wpndatabase.db
    command: python /app/cli_noc.py --prod watch
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 30 --label-enable
    environment:
      - REPO_USER=${DOCKER_USERNAME}
      - REPO_PASS=${DOCKER_PASSWORD}
